name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - ipykernel
  # - seaborn
  # - requests
  # - psutil
  # - python-kaleido
  # - python-graphviz
  - torchmetrics
  - scikit-learn=1.4.2
  - flask==3.0.1
  - ultralytics
  - opencv
  # - imutils
  # - confluent_kafka
