version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  broker:
    image: confluentinc/cp-kafka:7.4.1
    hostname: broker
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs-1
      KAFKA_MESSAGE_MAX_BYTES: 20971520
      KAFKA_REPLICA_FETCH_MAX_BYTES: 20971520
    networks:
      - kafka
      
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile-local
    image: stream-n-detect-producer-local
    depends_on:
      - broker
    volumes:
      - ./video:/video
    environment:
      - PARTITIONS_DETECT=2
      - TOPIC_DETECT=traffic
      - VIDEO_DIR=/video
    privileged: true
    networks:
      - kafka
      
  detector:
    build:
      context: ./detector
      dockerfile: Dockerfile-local
    image: stream-n-detect-detector-local
    depends_on:
      - producer
    volumes:
      - ./output:/output
    environment:
      - TOPIC_IN=traffic
      - OUTPUT_DIR=/output/detect
      - MODEL_PATH=/app/models/best.pt
    privileged: true
    networks:
      - kafka

  tracker:
    build:
      context: ./tracker
      dockerfile: Dockerfile-local
    image: stream-n-detect-tracker-local
    depends_on:
      - producer
    volumes:
      - ./output:/output
    environment:
      - BROKER = 'broker:9092' 
      - TOPIC_IN=traffic
      - OUTPUT_DIR=/output/track
      - MODEL_PATH=/app/models/best.pt
      - CLASSES_TO_COUNT = [2,3]
    networks:
      - kafka
      
networks:
  kafka:

volumes:
  output: