model_type: yolov8n.pt 
pretrained: True
seed: 0
imgsz: 640 
batch: 8 
epochs: 1
optimizer: SGD # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # learning rate 
name: 'yolov8n_exp_v0' # experiment name
project_dir: 'models'